version: '3'
services:
  sreader:
    build:
      context: ./sreader
    depends_on:
      - mosquitto
    restart: unless-stopped
    #privileged: true
    networks:
      - internal
    volumes:
      - ./etc/sreader.conf:/sreader/sreader.conf:ro
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/ttyAMA0:/dev/ttyAMA0"
    environment:
      - IOTSR_DEVICE_ID=${IOTSR_DEVICE_ID}
      - IOTSR_MQTT_HOST=mosquitto
    logging:
      driver: "json-file"
      options:
        max-size: "128k"
        max-file: "8"
  mosquitto:
    image: eclipse-mosquitto
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./etc/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto:/mosquitto/data
    logging:
      driver: "json-file"
      options:
        max-size: "128k"
        max-file: "8"

networks:
  internal:

volumes:
  mosquitto: